console.log("==".repeat(30));
var Addition1 = 5 + 3;
console.log(Addition1);
console.log("==".repeat(30));
var Subtraction1 = 16 - 8;
console.log(Subtraction1);
console.log("==".repeat(30));
var Multiplication1 = 2 * 4;
console.log(Multiplication1);
console.log("==".repeat(30));
var Division1 = 16 / 2;
console.log(Division1);
